@url = http://localhost:3000

### Hola Mundo
GET {{url}}/

### Listar todas las tareas
GET {{url}}/tareas

### Listar solo completadas
GET {{url}}/tareas?completada=true

### Listar solo pendientes
GET {{url}}/tareas?completada=false

### Crear una tarea
POST {{url}}/tareas
Content-Type: application/json

{
  "descripcion": "Comprar pan",
  "completada": false
}

### Obtener tarea por ID
GET {{url}}/tareas/1

### Eliminar tarea por ID
DELETE {{url}}/tareas/1
